---
- name: Update apt cache
  become: true
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Install Docker Packages
  become: true
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{ docker_packages }}"

- name: Download Docker GPG Key
  get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /tmp/docker.gpg

- name: Add Docker GPG Key
  become: true
  shell: apt-key add /tmp/docker.gpg

- name: Add Docker Repo to APT
  become: true
  apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} \ {{ ansible_distribution_release | lower }} \ stable"
      state: present

- name: Update Cache & Install Docker with APT
  become: true
  apt:
      update_cache: yes
      cache_valid_time: 3600
      name: "{{ item }}"
      state: present
  with_items:
      - docker-ce

- name: Install Docker Python Libs
  become: true
  pip: 
      name: docker-py
